Update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,6 +20,8 @@ jobs:
       check_scss: ${{ steps.scss_check.outputs.check_scss }}
       check_php: ${{ steps.php_check.outputs.check_php }}
       check_js: ${{ steps.js_check.outputs.check_js }}
+      language_check: ${{ steps.language_check.outputs.language_check }}
+      packagexml_check: ${{ steps.packagexml_check.outputs.packagexml_check }}
     steps:
       - uses: actions/checkout@v4
 
@@ -115,6 +117,73 @@ jobs:
             fi
           fi
 
+      - name: Validate plugin translations
+        id: language_check
+        run: |
+          if [ -d "./language" ]; then
+            required_files=("cs.xml" "da.xml" "de.xml" "en.xml" "es.xml" "fr.xml" "hu.xml" "it.xml" "nl.xml" "no.xml" "pl.xml" "ro.xml" "ru.xml" "sv.xml" "tr.xml")
+            missing_files=()
+          
+            for file in "${required_files[@]}"; do
+              if [ ! -f "./language/$file" ]; then
+                missing_files+=("$file")
+              fi
+            done
+          
+            if [ ${#missing_files[@]} -ne 0 ]; then
+              echo "Missing language files: ${missing_files[@]}"
+              echo "language_check=false" >> $GITHUB_OUTPUT
+              exit 1
+            else
+              echo "All required language files are present."
+              echo "language_check=true" >> $GITHUB_OUTPUT
+            fi
+          else
+            echo "./language directory does not exist. Skipping language file checks."
+            echo "language_check=true" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Validate package translations
+        id: packagexml_check
+        run: |
+          if [ -f "package.xml" ]; then
+            if ! command -v xmllint &> /dev/null; then
+              echo "xmllint could not be found. Installing libxml2-utils..."
+              sudo apt-get update
+              sudo apt-get install -y libxml2-utils
+            fi
+          
+            languages=("cs" "da" "de" "es" "fr" "hu" "it" "nl" "no" "pl" "ro" "ru" "sv" "tr")
+            missing_translations=()
+          
+            for lang in "${languages[@]}"; do
+              packagename_exists=$(xmllint --xpath "boolean(//*[local-name()='packagename'][@language='$lang'])" package.xml 2>/dev/null)
+              
+              if [ "$packagename_exists" != "true" ]; then
+                missing_translations+=("packagename[$lang]")
+                echo "Missing packagename for language: $lang"
+              fi
+
+              packagedescription_exists=$(xmllint --xpath "boolean(//*[local-name()='packagedescription'][@language='$lang'])" package.xml 2>/dev/null)
+              
+              if [ "$packagedescription_exists" != "true" ]; then
+                missing_translations+=("packagedescription[$lang]")
+                echo "Missing packagedescription for language: $lang"
+              fi
+            done
+          
+            if [ ${#missing_translations[@]} -ne 0 ]; then
+              echo "packagexml_check=false" >> $GITHUB_OUTPUT
+              exit 1
+            else
+              echo "All required package.xml translations are present."
+              echo "packagexml_check=true" >> $GITHUB_OUTPUT
+            fi
+          else
+            echo "package.xml does not exist. Skipping package.xml checks."
+            echo "packagexml_check=true" >> $GITHUB_OUTPUT
+          fi
+
   php:
     name: PHP Code Style, Fixes, and Syntax Check
     needs: init
@@ -127,18 +196,22 @@ jobs:
       fail-fast: false
     steps:
       - uses: actions/checkout@v4
+
       - name: Setup PHP ${{ matrix.php-version }}
         uses: shivammathur/setup-php@v2
         with:
           php-version: ${{ matrix.php-version }}
           extensions: ctype, dom, exif, gd, gmp, hash, intl, json, libxml, mbstring, opcache, pcre, pdo, pdo_mysql, zlib
           tools: cs2pr, phpcs, php-cs-fixer
+
       - name: PHP Code Style Check (phpcs)
         run: |
           phpcs -n -q --report=checkstyle | cs2pr
+
       - name: PHP Code Fix Check (php-cs-fixer)
         run: |
           php-cs-fixer fix --dry-run --diff
+
       - name: PHP Syntax Check
         run: |
           files_dirs=$(find . -type d -name 'files*')
@@ -148,6 +221,7 @@ jobs:
               ! find "$dir" -type f -name '*.php' -exec php -l '{}' \; 2>&1 |grep -v '^No syntax errors detected'
             done
           fi
+
       - name: Add PHP Syntax Matcher
         run: |
           echo "::add-matcher::.github/php-syntax.json"
@@ -159,26 +233,33 @@ jobs:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v4
+
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
           node-version: "20"
           cache: "npm"
+
       - name: Install Dependencies
         run: |
           npm install
+
       - name: TypeScript Syntax Check
         run: |
           npx tsc --noEmit
+
       - name: ESLint
         run: | 
           npx eslint .
+
       - name: Prettier Format Check
         run: |
           npx prettier --check "**/*.ts"
+
       - name: Show TypeScript Diff
         run: |
           git diff --exit-code -- '*.ts'
+
       - name: Add TypeScript Matcher
         run: |
           echo "::add-matcher::.github/diff.json"
@@ -190,14 +271,17 @@ jobs:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v4
+
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
           node-version: "20"
           cache: "npm"
+
       - name: Install Dependencies
         run: |
           npm install
+
       - name: Check JavaScript Syntax
         run: |
           files_dirs=$(find . -type d -name 'files*')
@@ -209,9 +293,11 @@ jobs:
                 sed "s@$(pwd)@.@" | grep '^'
             done
           fi
+
       - name: Add JavaScript Syntax Matcher
         run: |
           echo "::add-matcher::.github/javascript-syntax.json"
+
       - name: Show JavaScript Syntax Diff
         run: |
           git diff --exit-code -- '*.js'
@@ -223,25 +309,31 @@ jobs:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v4
+
       - name: Check for package.json
         id: check_files
         uses: andstor/file-existence-action@v3
         with:
           files: "package.json"
+
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
           node-version: "20"
           cache: "npm"
+
       - name: Install Dependencies
         run: |
           npm install
+
       - name: Run Prettier on SCSS
         run: |
           npx prettier --check "files/style/**/*.scss"
+
       - name: Show SCSS Diff
         run: |
           git diff --exit-code -- '*.scss'
+
       - name: Add SCSS Matcher
         run: |
           echo "::add-matcher::.github/diff.json"
@@ -253,24 +345,30 @@ jobs:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v4
+
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
           node-version: "20"
           cache: "npm"
+
       - name: Install Dependencies
         run: |
           npm install
+
       - name: Remove Specific Directories
         run: |
           rm -rf files/js/SoftCreatR/
           rm -rf files/js/MysteryCode/
+
       - name: Run TSC
         run: |
           npx tsc
+
       - name: Add JavaScript Sync Matcher
         run: |
           echo "::add-matcher::.github/diff.json"
+
       - name: Show JavaScript Sync Diff
         run: |
           git checkout -- package-lock.json
@@ -278,7 +376,15 @@ jobs:
 
   create-release:
     needs: [ init, php, typescript, javascript, scss, javascript_sync ]
-    if: always() && (startsWith(github.event.head_commit.message, '[Release]') || startsWith(github.ref, 'refs/tags/')) && !contains(needs.*.result, 'failure')
+    if: >
+      always() &&
+      (startsWith(github.event.head_commit.message, '[Release]') || startsWith(github.ref, 'refs/tags/')) &&
+      !contains(needs.init.result, 'failure') &&
+      !contains(needs.php.result, 'failure') &&
+      !contains(needs.typescript.result, 'failure') &&
+      !contains(needs.javascript.result, 'failure') &&
+      !contains(needs.scss.result, 'failure') &&
+      !contains(needs.javascript_sync.result, 'failure')
     runs-on: self-hosted
     permissions:
       contents: write
@@ -287,13 +393,16 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
       - name: List Existing Tags
         run: git tag -l
+
       - name: Clean Git Repository
         run: |
           git fetch --prune --tags
           git tag -d $(git tag) || true
           git fetch --tags
+
       - name: Get current version
         id: current-version
         run: |
@@ -309,21 +418,25 @@ jobs:
           else
             git tag -a "${{ env.version }}" -m "Release v${{ env.version }}"
           fi
+
       - name: Push Tag
         env:
           PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
         run: |
           git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git "${{ env.version }}"
+
       - name: Verify Tag Push
         run: |
           git fetch --tags
           git tag -l
+
       - name: Trigger Build Workflow
         uses: peter-evans/repository-dispatch@v3
         with:
           token: ${{ secrets.PAT_TOKEN }}
           event-type: Build
           client-payload: '{"tag": "${{ env.version }}"}'
+
       - name: Clean Workspace
         if: always()
         run: git clean -fdx && git reset --hard
